// --- 1. インポートデータベース ---
const db = {
    agency: [
        { id: 1, name: "SMILE-UP.", foundedYear: 1962, location: "東京都" },
        { id: 2, name: "STARTO ENTERTAINMENT", foundedYear: 2024, location: "東京都" }
    ],
    group: [
        { id: 1, name: "嵐", debutDate: "1999-11-03", status: "活動終了" },
        { id: 2, name: "SixTONES", debutDate: "2020-01-22", status: "活動中" },
        { id: 3, name: "Snow Man", debutDate: "2020-01-22", status: "活動中" },
        { id: 4, name: "SUPER EIGHT", debutDate: "2004-08-25", status: "活動中" },
        { id: 5, name: "NEWS", debutDate: "2003-11-07", status: "活動中" },
        { id: 6, name: "KAT-TUN", debutDate: "2006-03-22", status: "活動中" },
        { id: 7, name: "Hey! Say! JUMP", debutDate: "2007-11-14", status: "活動中" },
        { id: 8, name: "King & Prince", debutDate: "2018-05-23", status: "活動中" },
        { id: 9, name: "timelesz", debutDate: "2011-11-16", status: "活動中" },
        { id: 10, name: "WEST.", debutDate: "2014-04-23", status: "活動中" },
        { id: 11, name: "なにわ男子", debutDate: "2021-11-12", status: "活動中" },
        { id: 12, name: "Travis Japan", debutDate: "2022-10-28", status: "活動中" },
        { id: 13, name: "Aぇ! group", debutDate: "2024-05-15", status: "活動中" },
        { id: 14, name: "Kis-My-Ft2", debutDate: "2011-08-10", status: "活動中" },
        { id: 15, name: "TOKIO", debutDate: "1994-09-21", status: "活動中" },
        { id: 16, name: "V6", debutDate: "1995-11-01", status: "解散" },
        { id: 17, name: "KinKi Kids", debutDate: "1997-07-21", status: "活動中" }
    ],
    idol: [
        { id: 1, name: "大野智", birthday: "1980-11-26", status: "活動休止", agencyId: 2, memberColor: "青" },
        { id: 2, name: "櫻井翔", birthday: "1982-01-25", status: "活動中", agencyId: 2, memberColor: "赤" },
        { id: 3, name: "相葉雅紀", birthday: "1982-12-24", status: "活動中", agencyId: 2, memberColor: "緑" },
        { id: 4, name: "二宮和也", birthday: "1983-06-17", status: "活動中", agencyId: 2, memberColor: "黄" },
        { id: 5, name: "松本潤", birthday: "1983-08-30", status: "活動中", agencyId: 2, memberColor: "紫" },
        { id: 6, name: "ジェシー", birthday: "1996-06-11", status: "活動中", agencyId: 2, memberColor: "赤" },
        { id: 7, name: "京本大我", birthday: "1994-12-03", status: "活動中", agencyId: 2, memberColor: "ピンク" },
        { id: 8, name: "松村北斗", birthday: "1995-06-18", status: "活動中", agencyId: 2, memberColor: "黒" },
        { id: 9, name: "髙地優吾", birthday: "1994-03-08", status: "活動中", agencyId: 2, memberColor: "黄" },
        { id: 10, name: "森本慎太郎", birthday: "1997-07-15", status: "活動中", agencyId: 2, memberColor: "緑" },
        { id: 11, name: "田中樹", birthday: "1995-06-15", status: "活動中", agencyId: 2, memberColor: "青" },
        { id: 12, name: "目黒蓮", birthday: "1997-02-16", status: "活動中", agencyId: 2, memberColor: "黒" },
        { id: 13, name: "ラウール", birthday: "2003-06-27", status: "活動中", agencyId: 2, memberColor: "白" },
        { id: 14, name: "渡辺翔太", birthday: "1992-11-05", status: "活動中", agencyId: 2, memberColor: "青" },
        { id: 15, name: "向井康二", birthday: "1994-06-21", status: "活動中", agencyId: 2, memberColor: "オレンジ" },
        { id: 16, name: "山下智久", birthday: "1985-04-09", status: "活動中", agencyId: 2, memberColor: "赤" },
        { id: 17, name: "錦戸亮", birthday: "1984-11-03", status: "活動中", agencyId: 2, memberColor: "黄" },
        { id: 18, name: "内博貴", birthday: "1986-09-10", status: "活動休止", agencyId: 2, memberColor: "ピンク" },
        { id: 19, name: "岩本照", birthday: "1993-05-17", status: "活動中", agencyId: 2, memberColor: "黄" },
        { id: 20, name: "深澤辰哉", birthday: "1992-05-05", status: "活動中", agencyId: 2, memberColor: "紫" },
        { id: 21, name: "阿部亮平", birthday: "1993-11-27", status: "活動中", agencyId: 2, memberColor: "緑" },
        { id: 22, name: "宮舘涼太", birthday: "1993-03-25", status: "活動中", agencyId: 2, memberColor: "赤" },
        { id: 23, name: "佐久間大介", birthday: "1992-07-05", status: "活動中", agencyId: 2, memberColor: "ピンク" },
        { id: 24, name: "山田涼介", birthday: "1993-05-09", status: "活動中", agencyId: 2, memberColor: "赤" },
        { id: 25, name: "知念侑李", birthday: "1993-11-30", status: "活動中", agencyId: 2, memberColor: "ピンク" },
        { id: 26, name: "中島裕翔", birthday: "1993-08-10", status: "活動中", agencyId: 2, memberColor: "水色" },
        { id: 27, name: "永瀬廉", birthday: "1999-01-23", status: "活動中", agencyId: 2, memberColor: "漆黒" },
        { id: 28, name: "髙橋海人", birthday: "1999-04-03", status: "活動中", agencyId: 2, memberColor: "ひまわりイエロー" },
        { id: 29, name: "平野紫耀", birthday: "1997-01-29", status: "退所", agencyId: 2, memberColor: "真紅", notes: "退所後はTOBE所属。" },
        { id: 30, name: "神宮寺勇太", birthday: "1997-10-30", status: "退所", agencyId: 2, memberColor: "ターコイズブルー", notes: "退所後はTOBE所属。" },
        { id: 31, name: "岸優太", birthday: "1995-09-29", status: "退所", agencyId: 2, memberColor: "紫", notes: "退所後はTOBE所属。" },
        { id: 32, name: "亀梨和也", birthday: "1986-02-23", status: "活動中", agencyId: 2, memberColor: "ピンク" },
        { id: 33, name: "上田竜也", birthday: "1983-10-04", status: "活動中", agencyId: 2, memberColor: "青" },
        { id: 34, name: "中丸雄一", birthday: "1983-09-04", status: "活動中", agencyId: 2, memberColor: "紫" },
        { id: 35, name: "村上信五", birthday: "1982-01-26", status: "活動中", agencyId: 2, memberColor: "紫" },
        { id: 36, name: "丸山隆平", birthday: "1983-11-26", status: "活動中", agencyId: 2, memberColor: "オレンジ" },
        { id: 37, name: "安田章大", birthday: "1984-09-11", status: "活動中", agencyId: 2, memberColor: "青" },
        { id: 38, name: "大倉忠義", birthday: "1985-05-16", status: "活動中", agencyId: 2, memberColor: "緑" },
        { id: 39, name: "堂本光一", birthday: "1979-01-01", status: "活動中", agencyId: 2, memberColor: "赤" },
        { id: 40, name: "堂本剛", birthday: "1979-04-10", status: "活動中", agencyId: 2, memberColor: "青" },
        { id: 41, name: "城島茂", birthday: "1970-11-17", status: "活動中", agencyId: 2, memberColor: "緑" },
        { id: 42, name: "国分太一", birthday: "1974-09-02", status: "活動中", agencyId: 2, memberColor: "青" },
        { id: 43, name: "松岡昌宏", birthday: "1977-01-11", status: "活動中", agencyId: 2, memberColor: "紫" },
        { id: 44, name: "有岡大貴", birthday: "1991-04-15", status: "活動中", agencyId: 2, memberColor: "オレンジ" },
        { id: 45, name: "髙木雄也", birthday: "1990-03-26", status: "活動中", agencyId: 2, memberColor: "紫" },
        { id: 46, name: "伊野尾慧", birthday: "1990-06-22", status: "脱退", agencyId: 2, memberColor: "青" },
        { id: 47, name: "八乙女光", birthday: "1990-12-02", status: "活動中", agencyId: 2, memberColor: "黄" },
        { id: 48, name: "薮宏太", birthday: "1990-01-31", status: "活動中", agencyId: 2, memberColor: "黄緑" },
        { id: 49, name: "佐藤勝利", birthday: "1996-10-30", status: "活動中", agencyId: 2, memberColor: "赤" },
        { id: 50, name: "菊池風磨", birthday: "1995-03-07", status: "活動中", agencyId: 2, memberColor: "紫" },
        { id: 51, name: "松島聡", birthday: "1997-11-27", status: "活動中", agencyId: 2, memberColor: "緑" },
        { id: 52, name: "重岡大毅", birthday: "1992-08-26", status: "活動中", agencyId: 2, memberColor: "赤" },
        { id: 53, name: "桐山照史", birthday: "1989-08-31", status: "活動中", agencyId: 2, memberColor: "オレンジ" },
        { id: 54, name: "中間淳太", birthday: "1987-10-21", status: "活動中", agencyId: 2, memberColor: "黄" },
        { id: 55, name: "神山智洋", birthday: "1993-07-01", status: "活動中", agencyId: 2, memberColor: "緑" },
        { id: 56, name: "藤井流星", birthday: "1993-08-18", status: "活動中", agencyId: 2, memberColor: "青" },
        { id: 57, name: "濱田崇裕", birthday: "1988-12-19", status: "活動中", agencyId: 2, memberColor: "紫" },
        { id: 58, name: "小瀧望", birthday: "1996-07-30", status: "活動中", agencyId: 2, memberColor: "ピンク" },
        { id: 59, name: "西畑大吾", birthday: "1997-01-09", status: "活動中", agencyId: 2, memberColor: "赤" },
        { id: 60, name: "大西流星", birthday: "2001-08-07", status: "活動中", agencyId: 2, memberColor: "オレンジ" },
        { id: 61, name: "道枝駿佑", birthday: "2002-07-25", status: "活動中", agencyId: 2, memberColor: "ピンク" },
        { id: 62, name: "高橋恭平", birthday: "2000-02-28", status: "活動中", agencyId: 2, memberColor: "紫" },
        { id: 63, name: "長尾謙杜", birthday: "2002-08-15", status: "活動中", agencyId: 2, memberColor: "黄" },
        { id: 64, name: "藤原丈一郎", birthday: "1996-02-08", status: "活動中", agencyId: 2, memberColor: "青" },
        { id: 65, name: "大橋和也", birthday: "1997-08-09", status: "活動中", agencyId: 2, memberColor: "緑" },
        { id: 66, name: "宮近海斗", birthday: "1997-09-22", status: "活動中", agencyId: 2, memberColor: "赤" },
        { id: 67, name: "中村海人", birthday: "1997-04-15", status: "活動中", agencyId: 2, memberColor: "緑" },
        { id: 68, name: "七五三掛龍也", birthday: "1995-06-23", status: "活動中", agencyId: 2, memberColor: "ピンク" },
        { id: 69, name: "川島如恵留", birthday: "1994-11-22", status: "活動中", agencyId: 2, memberColor: "白" },
        { id: 70, name: "吉澤閑也", birthday: "1995-08-10", status: "活動中", agencyId: 2, memberColor: "黄" },
        { id: 71, name: "松田元太", birthday: "1999-04-19", status: "活動中", agencyId: 2, memberColor: "青" },
        { id: 72, name: "松倉海斗", birthday: "1997-11-14", status: "活動中", agencyId: 2, memberColor: "オレンジ" },
        { id: 73, name: "正門良規", birthday: "1996-11-28", status: "活動中", agencyId: 2, memberColor: "青" },
        { id: 74, name: "末澤誠也", birthday: "1994-08-24", status: "活動中", agencyId: 2, memberColor: "赤" },
        { id: 75, name: "草間リチャード敬太", birthday: "1996-01-11", status: "活動中", agencyId: 2, memberColor: "黄" },
        { id: 76, name: "小島健", birthday: "1999-06-25", status: "活動中", agencyId: 2, memberColor: "紫" },
        { id: 77, name: "佐野晶哉", birthday: "2002-03-13", status: "活動中", agencyId: 2, memberColor: "緑" },
        { id: 78, name: "藤ヶ谷太輔", birthday: "1987-06-25", status: "活動中", agencyId: 2, memberColor: "ピンク" },
        { id: 79, name: "玉森裕太", birthday: "1990-03-17", status: "活動中", agencyId: 2, memberColor: "黄" },
        { id: 80, name: "二階堂高嗣", birthday: "1990-08-06", status: "活動中", agencyId: 2, memberColor: "緑" },
        { id: 81, name: "千賀健永", birthday: "1991-03-23", status: "活動中", agencyId: 2, memberColor: "水色" },
        { id: 82, name: "宮田俊哉", birthday: "1988-09-14", status: "活動中", agencyId: 2, memberColor: "紫" },
        { id: 83, name: "横尾渉", birthday: "1986-05-16", status: "活動中", agencyId: 2, memberColor: "オレンジ" },
        { id: 84, name: "坂本昌行", birthday: "1971-07-24", status: "活動中", agencyId: 2, memberColor: "青" },
        { id: 85, name: "長野博", birthday: "1972-10-09", status: "活動中", agencyId: 2, memberColor: "purple" },
        { id: 86, name: "井ノ原快彦", birthday: "1976-05-17", status: "活動中", agencyId: 2, memberColor: "緑" },
        { id: 87, name: "森田剛", birthday: "1979-02-20", status: "退所", agencyId: 2, memberColor: "赤", notes: "退所後は個人活動。" },
        { id: 88, name: "三宅健", birthday: "1979-07-02", status: "退所", agencyId: 2, memberColor: "オレンジ", notes: "退所後はTOBE所属。" },
        { id: 89, name: "岡田准一", birthday: "1980-11-18", status: "退所", agencyId: 2, memberColor: "黄", notes: "退所後は個人活動。" },
        { id: 90, name: "寺西拓人", birthday: "1993-12-31", status: "活動中", agencyId: 2, memberColor: "水色" },
        { id: 91, name: "原嘉孝", birthday: "1995-09-25", status: "活動中", agencyId: 2, memberColor: "黄緑" },
        { id: 92, name: "橋本将生", birthday: "2000-01-01", status: "活動中", agencyId: 2, memberColor: "ピンク" },
        { id: 93, name: "猪俣周杜", birthday: "2001-02-02", status: "活動中", agencyId: 2, memberColor: "黄" },
        { id: 94, name: "篠塚大輝", birthday: "2002-03-03", status: "活動中", agencyId: 2, memberColor: "白" },
    ],
    // 中間テーブル: グループ所属 (非表示タブ)
    affiliation: [
        { id: 1, idolId: 1, groupId: 1, status: "活動休止", role: "リーダー", isConcurrent: "false" },
        { id: 2, idolId: 2, groupId: 1, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 3, idolId: 3, groupId: 1, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 4, idolId: 4, groupId: 1, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 5, idolId: 5, groupId: 1, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 6, idolId: 6, groupId: 2, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 7, idolId: 7, groupId: 2, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 8, idolId: 8, groupId: 2, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 9, idolId: 9, groupId: 2, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 10, idolId: 10, groupId: 2, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 11, idolId: 11, groupId: 2, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 12, idolId: 12, groupId: 3, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 13, idolId: 13, groupId: 3, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 14, idolId: 14, groupId: 3, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 15, idolId: 15, groupId: 3, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 16, idolId: 17, groupId: 4, status: "脱退", role: "メンバー", isConcurrent: "false" },
        { id: 17, idolId: 17, groupId: 5, status: "脱退", role: "メンバー", isConcurrent: "true" },
        { id: 18, idolId: 16, groupId: 5, status: "脱退", role: "メンバー", isConcurrent: "true" },
        { id: 19, idolId: 18, groupId: 5, status: "活動休止", role: "メンバー", isConcurrent: "true" },
        { id: 20, idolId: 18, groupId: 4, status: "活動休止", role: "メンバー", isConcurrent: "true" },
        { id: 21, idolId: 19, groupId: 3, status: "在籍中", role: "リーダー", isConcurrent: "false" },
        { id: 22, idolId: 20, groupId: 3, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 23, idolId: 21, groupId: 3, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 24, idolId: 22, groupId: 3, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 25, idolId: 23, groupId: 3, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 26, idolId: 24, groupId: 7, status: "在籍中", role: "センター", isConcurrent: "false" },
        { id: 27, idolId: 25, groupId: 7, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 28, idolId: 26, groupId: 7, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 29, idolId: 27, groupId: 8, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 30, idolId: 28, groupId: 8, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 31, idolId: 29, groupId: 8, status: "脱退", role: "センター", isConcurrent: "false" },
        { id: 32, idolId: 30, groupId: 8, status: "脱退", role: "メンバー", isConcurrent: "false" },
        { id: 33, idolId: 31, groupId: 8, status: "脱退", role: "リーダー", isConcurrent: "false" },
        { id: 34, idolId: 32, groupId: 6, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 35, idolId: 33, groupId: 6, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 36, idolId: 34, groupId: 6, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 37, idolId: 35, groupId: 4, status: "在籍中", role: "MC", isConcurrent: "false" },
        { id: 38, idolId: 36, groupId: 4, status: "在籍中", role: "ベース", isConcurrent: "false" },
        { id: 39, idolId: 37, groupId: 4, status: "在籍中", role: "ギター", isConcurrent: "false" },
        { id: 40, idolId: 38, groupId: 4, status: "在籍中", role: "ドラム", isConcurrent: "false" },
        { id: 41, idolId: 39, groupId: 17, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 42, idolId: 40, groupId: 17, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 43, idolId: 41, groupId: 15, status: "在籍中", role: "リーダー", isConcurrent: "false" },
        { id: 44, idolId: 42, groupId: 15, status: "在籍中", role: "キーボード", isConcurrent: "false" },
        { id: 45, idolId: 43, groupId: 15, status: "在籍中", role: "ドラム", isConcurrent: "false" },
        { id: 46, idolId: 44, groupId: 7, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 47, idolId: 45, groupId: 7, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 48, idolId: 46, groupId: 7, status: "脱退", role: "メンバー", isConcurrent: "false" },
        { id: 49, idolId: 47, groupId: 7, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 50, idolId: 48, groupId: 7, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 51, idolId: 49, groupId: 9, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 52, idolId: 50, groupId: 9, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 53, idolId: 51, groupId: 9, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 54, idolId: 52, groupId: 10, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 55, idolId: 53, groupId: 10, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 56, idolId: 54, groupId: 10, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 57, idolId: 55, groupId: 10, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 58, idolId: 56, groupId: 10, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 59, idolId: 57, groupId: 10, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 60, idolId: 58, groupId: 10, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 61, idolId: 59, groupId: 11, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 62, idolId: 60, groupId: 11, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 63, idolId: 61, groupId: 11, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 64, idolId: 62, groupId: 11, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 65, idolId: 63, groupId: 11, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 66, idolId: 64, groupId: 11, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 67, idolId: 65, groupId: 11, status: "在籍中", role: "リーダー", isConcurrent: "false" },
        { id: 68, idolId: 66, groupId: 12, status: "在籍中", role: "リーダー", isConcurrent: "false" },
        { id: 69, idolId: 67, groupId: 12, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 70, idolId: 68, groupId: 12, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 71, idolId: 69, groupId: 12, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 72, idolId: 70, groupId: 12, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 73, idolId: 71, groupId: 12, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 74, idolId: 72, groupId: 12, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 75, idolId: 73, groupId: 13, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 76, idolId: 74, groupId: 13, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 77, idolId: 75, groupId: 13, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 78, idolId: 76, groupId: 13, status: "在籍中", role: "リーダー", isConcurrent: "false" },
        { id: 79, idolId: 77, groupId: 13, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 80, idolId: 78, groupId: 14, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 81, idolId: 79, groupId: 14, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 82, idolId: 80, groupId: 14, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 83, idolId: 81, groupId: 14, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 84, idolId: 82, groupId: 14, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 85, idolId: 83, groupId: 14, status: "在籍中", role: "メンバー", isConcurrent: "false" },
        { id: 86, idolId: 84, groupId: 16, status: "脱退", role: "リーダー", isConcurrent: "false" },
        { id: 87, idolId: 85, groupId: 16, status: "脱退", role: "メンバー", isConcurrent: "false" },
        { id: 88, idolId: 86, groupId: 16, status: "脱退", role: "メンバー", isConcurrent: "false" },
        { id: 89, idolId: 87, groupId: 16, status: "脱退", role: "メンバー", isConcurrent: "false" },
        { id: 90, idolId: 88, groupId: 16, status: "脱退", role: "メンバー", isConcurrent: "false" },
        { id: 91, idolId: 89, groupId: 16, status: "脱退", role: "メンバー", isConcurrent: "false" },
        { id: 92, idolId: 90, groupId: 9, status: "在籍中", role: "追加メンバー", isConcurrent: "false" },
        { id: 93, idolId: 91, groupId: 9, status: "在籍中", role: "追加メンバー", isConcurrent: "false" },
        { id: 94, idolId: 92, groupId: 9, status: "在籍中", role: "追加メンバー", isConcurrent: "false" },
        { id: 95, idolId: 93, groupId: 9, status: "在籍中", role: "追加メンバー", isConcurrent: "false" },
        { id: 96, idolId: 94, groupId: 9, status: "在籍中", role: "追加メンバー", isConcurrent: "false" }
    ],
    groupHistory: [
        { id: 1, groupId: 4, oldName: "関ジャニ∞", newName: "SUPER EIGHT", changeDate: "2024-02-04" },
        { id: 2, groupId: 9, oldName: "Sexy Zone", newName: "timelesz", changeDate: "2024-04-01" },
        { id: 3, groupId: 10, oldName: "ジャニーズWEST", newName: "WEST.", changeDate: "2023-10-18" },
        { id: 4, groupId: 13, oldName: "Aぇ! group (関西ジュニア)", newName: "Aぇ! group", changeDate: "2024-05-15" },
        { id: 5, groupId: 8, oldName: "King & Prince (5人体制)", newName: "King & Prince (2人体制)", changeDate: "2023-05-23" },
        { id: 6, groupId: 6, oldName: "KAT-TUN (6人体制)", newName: "KAT-TUN", changeDate: "2010-07-16" }
    ],
    // 作品マスタ (旧番組・メガ拡張データ追加完了)
    work: [
        { id: 1, title: "A・RA・SHI", type: "シングル", publisher: "ポニーキャニオン", releaseDate: "1999-11-03" },
        { id: 2, title: "Love so sweet", type: "シングル", publisher: "J Storm", releaseDate: "2007-02-21" },
        { id: 3, title: "Imitation Rain", type: "シングル", publisher: "ソニー・ミュージック", releaseDate: "2020-01-22" },
        { id: 4, title: "NAVIGATOR", type: "シングル", publisher: "ソニー・ミュージック", releaseDate: "2020-07-22" },
        { id: 5, title: "silent", type: "ドラマ", publisher: "フジテレビ", releaseDate: "2022-10-06" },
        { id: 6, title: "青春アミーゴ", type: "シングル", publisher: "ジャニーズ・エンタテイメント", releaseDate: "2005-11-02" },
        { id: 7, title: "硝子の少年", type: "シングル", publisher: "ジャニーズ・エンタテイメント", releaseDate: "1997-07-21" },
        { id: 8, title: "シンデレラガール", type: "シングル", publisher: "Johnnys' Universe", releaseDate: "2018-05-23" },
        { id: 9, title: "D.D.", type: "シングル", publisher: "avex trax", releaseDate: "2020-01-22" },
        { id: 10, title: "Real Face", type: "シングル", publisher: "J-One Records", releaseDate: "2006-03-22" },
        { id: 11, title: "クロサギ", type: "ドラマ", publisher: "TBS", releaseDate: "2006-04-14" },
        { id: 12, title: "ごくせん 第2シリーズ", type: "ドラマ", publisher: "日本テレビ", releaseDate: "2005-01-15" },
        { id: 13, title: "Happiness", type: "シングル", publisher: "J Storm", releaseDate: "2007-09-05" },
        { id: 14, title: "感謝カンゲキ雨嵐", type: "シングル", publisher: "ポニーキャニオン", releaseDate: "2000-11-08" },
        { id: 15, title: "ワイルド アット ハート", type: "シングル", publisher: "J Storm", releaseDate: "2012-03-07" },
        { id: 16, title: "truth", type: "シングル", publisher: "J Storm", releaseDate: "2008-08-20" },
        { id: 17, title: "Monster", type: "シングル", publisher: "J Storm", releaseDate: "2010-05-19" },
        { id: 18, title: "果てない空", type: "シングル", publisher: "J Storm", releaseDate: "2010-11-10" },
        { id: 19, title: "迷宮ラブソング", type: "シングル", publisher: "J Storm", releaseDate: "2011-11-02" },
        { id: 20, title: "GUTS!", type: "シングル", publisher: "J Storm", releaseDate: "2014-04-30" },
        { id: 21, title: "Sakura", type: "シングル", publisher: "J Storm", releaseDate: "2015-02-25" },
        { id: 22, title: "NEW ERA", type: "シングル", publisher: "ソニー・ミュージック", releaseDate: "2020-11-11" },
        { id: 23, title: "僕が僕じゃないみたいだ", type: "シングル", publisher: "ソニー・ミュージック", releaseDate: "2021-02-17" },
        { id: 24, title: "マスカラ", type: "シングル", publisher: "ソニー・ミュージック", releaseDate: "2021-08-11" },
        { id: 25, title: "わたし", type: "シングル", publisher: "ソニー・ミュージック", releaseDate: "2022-06-08" },
        { id: 26, title: "共鳴", type: "シングル", publisher: "ソニー・ミュージック", releaseDate: "2022-03-02" },
        { id: 27, title: "KISSIN' MY LIPS", type: "シングル", publisher: "avex trax", releaseDate: "2020-10-07" },
        { id: 28, title: "Grandeur", type: "シングル", publisher: "avex trax", releaseDate: "2021-01-20" },
        { id: 29, title: "HELLO HELLO", type: "シングル", publisher: "avex trax", releaseDate: "2021-07-14" },
        { id: 30, title: "Secret Touch", type: "シングル", publisher: "avex trax", releaseDate: "2021-12-01" },
        { id: 31, title: "ブラザービート", type: "シングル", publisher: "MENT RECORDING", releaseDate: "2022-03-30" },
        { id: 32, title: "Memorial", type: "シングル", publisher: "Johnnys' Universe", releaseDate: "2018-10-10" },
        { id: 33, title: "koi-wazurai", type: "シングル", publisher: "Johnnys' Universe", releaseDate: "2019-08-28" },
        { id: 34, title: "Mazy Night", type: "シングル", publisher: "Johnnys' Universe", releaseDate: "2020-06-10" },
        { id: 35, title: "I promise", type: "シングル", publisher: "Johnnys' Universe", releaseDate: "2020-12-16" },
        { id: 36, title: "ツキヨミ", type: "シングル", publisher: "Johnnys' Universe", releaseDate: "2022-11-09" },
        { id: 37, title: "初心LOVE", type: "シングル", publisher: "J Storm", releaseDate: "2021-11-12" },
        { id: 38, title: "The Answer", type: "シングル", publisher: "J Storm", releaseDate: "2022-04-27" },
        { id: 39, title: "サチアレ", type: "シングル", publisher: "J Storm", releaseDate: "2022-04-27" },
        { id: 40, title: "愛されるより 愛したい", type: "シングル", publisher: "ジャニーズ・エンタテイメント", releaseDate: "1997-11-12" },
        { id: 41, title: "全部だきしめて", type: "シングル", publisher: "ジャニーズ・エンタテイメント", releaseDate: "1998-07-29" },
        { id: 42, title: "青の時代", type: "シングル", publisher: "ジャニーズ・エンタテイメント", releaseDate: "1998-07-29" },
        { id: 43, title: "99.9-刑事専門弁護士-", type: "ドラマ", publisher: "TBS", releaseDate: "2016-04-17" },
        { id: 44, title: "マイファミリー", type: "ドラマ", publisher: "TBS", releaseDate: "2022-04-10" },
        { id: 45, title: "謎解きはディナーのあとで", type: "ドラマ", publisher: "フジテレビ", releaseDate: "2011-10-18" },
        { id: 46, title: "ごくせん 第1シリーズ", type: "ドラマ", publisher: "日本テレビ", releaseDate: "2002-04-17" },
        { id: 47, title: "金田一少年の事件簿", type: "ドラマ", publisher: "日本テレビ", releaseDate: "1995-07-15" },
        { id: 48, title: "野ブタ。をプロデュース", type: "ドラマ", publisher: "日本テレビ", releaseDate: "2005-10-15" },
        { id: 49, title: "VS嵐", type: "バラエティ", publisher: "フジテレビ", releaseDate: "2008-04-12" },
        { id: 50, title: "ザ！鉄腕！DASH!!", type: "バラエティ", publisher: "日本テレビ", releaseDate: "1995-11-02" },
        { id: 51, title: "月曜から夜ふかし", type: "バラエティ", publisher: "日本テレビ", releaseDate: "2012-04-09" },
        { id: 52, title: "櫻井・有吉 THE夜会", type: "バラエティ", publisher: "TBS", releaseDate: "2014-04-17" },
        { id: 53, title: "嵐にしやがれ", type: "バラエティ", publisher: "日本テレビ", releaseDate: "2010-04-24" },
        { id: 54, title: "それSnow Manにやらせて下さい", type: "バラエティ", publisher: "TBS", releaseDate: "2021-04-11" },
        { id: 55, title: "SixTONESのオールナイトニッポンサタデースペシャル", type: "ラジオ", publisher: "ニッポン放送", releaseDate: "2020-04-04" },
        { id: 56, title: "EIGHT-JAM", type: "音楽番組", publisher: "テレビ朝日", releaseDate: "2015-05-10" },
        { id: 57, title: "KinKi Kidsのブンブブーン", type: "バラエティ", publisher: "フジテレビ", releaseDate: "2014-10-26" },
        { id: 58, title: "スクール革命！", type: "バラエティ", publisher: "日本テレビ", releaseDate: "2009-04-05" },
        { id: 59, title: "キスマイ超BUSAIKU!?", type: "バラエティ", publisher: "フジテレビ", releaseDate: "2013-04-21" },
        { id: 60, title: "なにわ男子の逆転男子", type: "バラエティ", publisher: "テレビ朝日", releaseDate: "2023-07-01" },
        { id: 61, title: "A-Studio+", type: "バラエティ", publisher: "TBS", releaseDate: "2009-04-10" },
        { id: 62, title: "相葉マナブ", type: "バラエティ", publisher: "テレビ朝日", releaseDate: "2013-04-21" },
        { id: 63, title: "ニノさん", type: "バラエティ", publisher: "日本テレビ", releaseDate: "2013-04-25" },
        { id: 64, title: "NEWS ZERO", type: "報道", publisher: "日本テレビ", releaseDate: "2006-10-02" },
        { id: 65, title: "キントレ", type: "バラエティ", publisher: "日本テレビ", releaseDate: "2023-07-01" },
        { id: 66, title: "ザ少年倶楽部", type: "音楽番組", publisher: "NHK BSプレミアム", releaseDate: "2000-04-09" },
        { id: 67, title: "KAT-TUNの世界一タメになる旅!", type: "バラエティ", publisher: "TBS", releaseDate: "2014-01-11" },
        { id: 68, title: "トキタビ", type: "バラエティ", publisher: "フジテレビ", releaseDate: "2023-10-07" },
        { id: 69, title: "V6の愛なんだ", type: "バラエティ", publisher: "TBS", releaseDate: "2017-08-30" },
        { id: 70, title: "Time", type: "アルバム", publisher: "J Storm", releaseDate: "2007-07-11" },
        { id: 71, title: "5×10 All the BEST! 1999-2009", type: "アルバム", publisher: "J Storm", releaseDate: "2009-08-19" },
        { id: 72, title: "Japonism", type: "アルバム", publisher: "J Storm", releaseDate: "2015-10-21" },
        { id: 73, title: "ARASHI Anniversary Tour 5×20", type: "映像作品", publisher: "J Storm", releaseDate: "2020-09-30" },
        { id: 74, title: "鍵のかかった部屋", type: "ドラマ", publisher: "フジテレビ", releaseDate: "2012-04-16" },
        { id: 75, title: "フリーター、家を買う。", type: "ドラマ", publisher: "フジテレビ", releaseDate: "2010-10-19" },
        { id: 76, title: "マイガール", type: "ドラマ", publisher: "テレビ朝日", releaseDate: "2009-10-09" },
        { id: 77, title: "Good Luck!", type: "シングル", publisher: "ソニー・ミュージック", releaseDate: "2022-11-02" },
        { id: 78, title: "こっから", type: "シングル", publisher: "ソニー・ミュージック", releaseDate: "2023-06-14" },
        { id: 79, title: "アンセム", type: "シングル", publisher: "ソニー・ミュージック", releaseDate: "2024-01-10" },
        { id: 80, title: "1ST", type: "アルバム", publisher: "ソニー・ミュージック", releaseDate: "2021-01-06" },
        { id: 81, title: "CITY", type: "アルバム", publisher: "ソニー・ミュージック", releaseDate: "2022-01-05" },
        { id: 82, title: "声", type: "アルバム", publisher: "ソニー・ミュージック", releaseDate: "2023-01-04" },
        { id: 83, title: "THE VIBES", type: "アルバム", publisher: "ソニー・ミュージック", releaseDate: "2024-01-10" },
        { id: 84, title: "バリューの真実", type: "バラエティ", publisher: "NHK Eテレ", releaseDate: "2020-12-20" },
        { id: 85, title: "タペストリー / W", type: "シングル", publisher: "MENT RECORDING", releaseDate: "2023-03-15" },
        { id: 86, title: "Dangerholic", type: "シングル", publisher: "MENT RECORDING", releaseDate: "2023-09-06" },
        { id: 87, title: "LOVE TRIGGER / We'll go together", type: "シングル", publisher: "MENT RECORDING", releaseDate: "2024-02-14" },
        { id: 88, title: "Snow Mania S1", type: "アルバム", publisher: "avex trax", releaseDate: "2021-09-29" },
        { id: 89, title: "Snow Labo. S2", type: "アルバム", publisher: "MENT RECORDING", releaseDate: "2022-09-21" },
        { id: 90, title: "i DO ME", type: "アルバム", publisher: "MENT RECORDING", releaseDate: "2023-05-17" },
        { id: 91, title: "おそ松さん", type: "映画", publisher: "東宝", releaseDate: "2022-03-25" },
        { id: 92, title: "滝沢歌舞伎 ZERO 2020 The Movie", type: "映画", publisher: "松竹", releaseDate: "2020-12-04" },
        { id: 93, title: "ズッコケ男道", type: "シングル", publisher: "インペリアルレコード", releaseDate: "2007-04-11" },
        { id: 94, title: "無責任ヒーロー", type: "シングル", publisher: "インペリアルレコード", releaseDate: "2008-10-29" },
        { id: 95, title: "LIFE〜目の前の向こうへ〜", type: "シングル", publisher: "インペリアルレコード", releaseDate: "2010-08-25" },
        { id: 96, title: "ありえへん∞世界", type: "バラエティ", publisher: "テレビ東京", releaseDate: "2008-04-15" },
        { id: 97, title: "関ジャニ∞の ジャニ勉", type: "バラエティ", publisher: "関西テレビ", releaseDate: "2007-05-02" },
        { id: 98, title: "チャンカパーナ", type: "シングル", publisher: "ジャニーズ・エンタテイメント", releaseDate: "2012-07-18" },
        { id: 99, title: "weeeek", type: "シングル", publisher: "ジャニーズ・エンタテイメント", releaseDate: "2007-11-07" },
        { id: 100, title: "さくらガール", type: "シングル", publisher: "ジャニーズ・エンタテイメント", releaseDate: "2010-03-31" },
        { id: 101, title: "NEWSな2人", type: "バラエティ", publisher: "TBS", releaseDate: "2015-07-03" },
        { id: 102, title: "Keep the faith", type: "シングル", publisher: "J-One Records", releaseDate: "2007-11-21" },
        { id: 103, title: "DON'T U EVER STOP", type: "シングル", publisher: "J-One Records", releaseDate: "2008-05-14" },
        { id: 104, title: "妖怪人間ベム", type: "ドラマ", publisher: "日本テレビ", releaseDate: "2011-10-22" },
        { id: 105, title: "Ultra Music Power", type: "シングル", publisher: "J Storm", releaseDate: "2007-11-14" },
        { id: 106, title: "ウィークエンダー", type: "シングル", publisher: "J Storm", releaseDate: "2014-09-03" },
        { id: 107, title: "White Love", type: "シングル", publisher: "J Storm", releaseDate: "2017-12-20" },
        { id: 108, title: "ネガティブファイター", type: "シングル", publisher: "J Storm", releaseDate: "2021-05-12" },
        { id: 109, title: "いただきハイジャンプ", type: "バラエティ", publisher: "フジテレビ", releaseDate: "2015-07-08" },
        { id: 110, title: "Magic Touch", type: "シングル", publisher: "Johnnys' Universe", releaseDate: "2021-05-19" },
        { id: 111, title: "踊るように人生を。", type: "シングル", publisher: "Johnnys' Universe", releaseDate: "2022-04-13" },
        { id: 112, title: "TraceTrace", type: "シングル", publisher: "Johnnys' Universe", releaseDate: "2022-09-14" },
        { id: 113, title: "L&", type: "アルバム", publisher: "Johnnys' Universe", releaseDate: "2020-09-02" },
        { id: 114, title: "Re:Sense", type: "アルバム", publisher: "Johnnys' Universe", releaseDate: "2021-07-21" },
        { id: 115, title: "Made in", type: "アルバム", publisher: "Johnnys' Universe", releaseDate: "2022-06-29" },
        { id: 116, title: "Mr.5", type: "アルバム", publisher: "Johnnys' Universe", releaseDate: "2023-04-19" },
        { id: 117, title: "ピース", type: "アルバム", publisher: "Johnnys' Universe", releaseDate: "2023-08-16" },
        { id: 118, title: "Sexy Zone", type: "シングル", publisher: "ポニーキャニオン", releaseDate: "2011-11-16" },
        { id: 119, title: "RUN", type: "シングル", publisher: "Top J Records", releaseDate: "2020-08-05" },
        { id: 120, title: "夏のハイドレンジア", type: "シングル", publisher: "Top J Records", releaseDate: "2021-08-04" },
        { id: 121, title: "本音と建前", type: "シングル", publisher: "Top J Records", releaseDate: "2023-09-20" },
        { id: 122, title: "Sexy Zoneの進化論", type: "バラエティ", publisher: "フジテレビTWO", releaseDate: "2020-04-10" },
        { id: 123, title: "ええじゃないか", type: "シングル", publisher: "ジャニーズ・エンタテイメント", releaseDate: "2014-04-23" },
        { id: 124, title: "証拠", type: "シングル", publisher: "ジャニーズ・エンタテイメント", releaseDate: "2020-06-24" },
        { id: 125, title: "星の雨", type: "シングル", publisher: "ジャニーズ・エンタテイメント", releaseDate: "2022-08-03" },
        { id: 126, title: "リア突WEST", type: "バラエティ", publisher: "朝日放送", releaseDate: "2020-10-03" },
        { id: 127, title: "ハッピーサプライズ", type: "シングル", publisher: "J Storm", releaseDate: "2022-11-16" },
        { id: 128, title: "Special Kiss", type: "シングル", publisher: "J Storm", releaseDate: "2023-03-08" },
        { id: 129, title: "Make Up Day", type: "シングル", publisher: "J Storm", releaseDate: "2023-09-13" },
        { id: 130, title: "消えた初恋", type: "ドラマ", publisher: "テレビ朝日", releaseDate: "2021-10-09" },
        { id: 131, title: "金田一少年の事件簿(第5シリーズ)", type: "ドラマ", publisher: "日本テレビ", releaseDate: "2022-04-24" },
        { id: 132, title: "JUST DANCE!", type: "シングル", publisher: "Capitol Records", releaseDate: "2022-10-28" },
        { id: 133, title: "Candy Kiss", type: "シングル", publisher: "Capitol Records", releaseDate: "2023-07-03" },
        { id: 134, title: "《A》BEGINNING", type: "シングル", publisher: "ユニバーサルミュージック", releaseDate: "2024-05-15" },
        { id: 135, title: "Aぇ!!!!!!ゐこ", type: "バラエティ", publisher: "MBS", releaseDate: "2023-10-14" },
        { id: 136, title: "Everybody Go", type: "シングル", publisher: "avex trax", releaseDate: "2011-08-10" },
        { id: 137, title: "SHE! HER! HER!", type: "シングル", publisher: "avex trax", releaseDate: "2012-03-21" },
        { id: 138, title: "Luv Bias", type: "シングル", publisher: "avex trax", releaseDate: "2021-02-24" },
        { id: 139, title: "10万円でできるかな", type: "バラエティ", publisher: "テレビ朝日", releaseDate: "2017-10-04" },
        { id: 140, title: "AMBITIOUS JAPAN!", type: "シングル", publisher: "ユニバーサルJ", releaseDate: "2003-10-01" },
        { id: 141, title: "宙船", type: "シングル", publisher: "ユニバーサルJ", releaseDate: "2006-08-23" },
        { id: 142, title: "MUSIC FOR THE PEOPLE", type: "シングル", publisher: "avex trax", releaseDate: "1995-11-01" },
        { id: 143, title: "WAになっておどろう", type: "シングル", publisher: "avex trax", releaseDate: "1997-07-09" },
        { id: 144, title: "Darling", type: "シングル", publisher: "avex trax", releaseDate: "2003-05-28" },
        { id: 145, title: "ボクの背中には羽根がある", type: "シングル", publisher: "ジャニーズ・エンタテイメント", releaseDate: "2001-02-07" },
        { id: 146, title: "Anniversary", type: "シングル", publisher: "ジャニーズ・エンタテイメント", releaseDate: "2004-12-22" }
    ],
    // 中間テーブル: 作品参加
    participation: [
        { id: 1, workId: 5, idolId: 12, role: "出演 (佐倉想)" },
        { id: 2, workId: 5, idolId: 8, role: "出演" },
        { id: 3, workId: 6, idolId: 16, role: "歌唱・メイン" },
        { id: 4, workId: 7, idolId: 39, role: "歌唱" },
        { id: 5, workId: 7, idolId: 40, role: "歌唱" },
        { id: 6, workId: 8, idolId: 29, role: "歌唱・センター" },
        { id: 7, workId: 8, idolId: 27, role: "歌唱" },
        { id: 8, workId: 9, idolId: 13, role: "歌唱・センター" },
        { id: 9, workId: 10, idolId: 32, role: "歌唱" },
        { id: 10, workId: 11, idolId: 16, role: "出演 (主演)" },
        { id: 11, workId: 12, idolId: 32, role: "出演 (小田切竜)" },
        { id: 12, workId: 49, idolId: 2, role: "MC" },
        { id: 13, workId: 50, idolId: 41, role: "レギュラー (メイン)" },
        { id: 14, workId: 50, idolId: 42, role: "レギュラー (メイン)" },
        { id: 15, workId: 50, idolId: 43, role: "レギュラー (メイン)" },
        { id: 16, workId: 50, idolId: 10, role: "レギュラー" },
        { id: 17, workId: 51, idolId: 35, role: "MC" },
        { id: 18, workId: 52, idolId: 2, role: "MC" },
        { id: 19, workId: 61, idolId: 78, role: "MC" },
        { id: 20, workId: 62, idolId: 3, role: "MC" },
        { id: 21, workId: 63, idolId: 4, role: "MC" },
        { id: 22, workId: 64, idolId: 2, role: "キャスター" },
        { id: 23, workId: 74, idolId: 1, role: "出演 (榎本径)" },
        { id: 24, workId: 75, idolId: 4, role: "出演 (武誠治)" },
        { id: 25, workId: 76, idolId: 3, role: "出演 (笠間正宗)" },
        { id: 26, workId: 104, idolId: 32, role: "出演 (ベム)" },
        { id: 27, workId: 130, idolId: 61, role: "出演 (青木想太)" },
        { id: 28, workId: 131, idolId: 61, role: "出演 (金田一一)" },
        { id: 29, workId: 47, idolId: 40, role: "出演 (金田一一)" },
        { id: 30, workId: 1, idolId: 1, role: "歌唱" },
        { id: 31, workId: 1, idolId: 2, role: "歌唱" },
        { id: 32, workId: 1, idolId: 3, role: "歌唱" },
        { id: 33, workId: 1, idolId: 4, role: "歌唱" },
        { id: 34, workId: 1, idolId: 5, role: "歌唱" },
        { id: 35, workId: 2, idolId: 1, role: "歌唱" },
        { id: 36, workId: 2, idolId: 2, role: "歌唱" },
        { id: 37, workId: 2, idolId: 3, role: "歌唱" },
        { id: 38, workId: 2, idolId: 4, role: "歌唱" },
        { id: 39, workId: 2, idolId: 5, role: "歌唱" },
        { id: 41, workId: 3, idolId: 6, role: "歌唱" },
        { id: 42, workId: 3, idolId: 7, role: "歌唱" },
        { id: 43, workId: 3, idolId: 8, role: "歌唱" },
        { id: 44, workId: 3, idolId: 9, role: "歌唱" },
        { id: 45, workId: 3, idolId: 10, role: "歌唱" },
        { id: 46, workId: 3, idolId: 11, role: "歌唱" },
        { id: 47, workId: 48, idolId: 39, role: "MC" },
        { id: 48, workId: 48, idolId: 40, role: "MC" },
        { id: 49, workId: 132, idolId: 66, role: "歌唱" },
        { id: 50, workId: 135, idolId: 73, role: "歌唱" },
        { id: 51, workId: 1, groupId: 1, role: "歌唱（グループ）" },
        { id: 52, workId: 2, groupId: 1, role: "歌唱（グループ）" },
        { id: 53, workId: 13, groupId: 1, role: "歌唱（グループ）" },
        { id: 54, workId: 14, groupId: 1, role: "歌唱（グループ）" },
        { id: 55, workId: 15, groupId: 1, role: "歌唱（グループ）" },
        { id: 56, workId: 16, groupId: 1, role: "歌唱（グループ）" },
        { id: 57, workId: 17, groupId: 1, role: "歌唱（グループ）" },
        { id: 58, workId: 18, groupId: 1, role: "歌唱（グループ）" },
        { id: 59, workId: 19, groupId: 1, role: "歌唱（グループ）" },
        { id: 60, workId: 20, groupId: 1, role: "歌唱（グループ）" },
        { id: 61, workId: 21, groupId: 1, role: "歌唱（グループ）" },
        { id: 62, workId: 3, groupId: 2, role: "歌唱（グループ）" },
        { id: 63, workId: 4, groupId: 2, role: "歌唱（グループ）" },
        { id: 64, workId: 22, groupId: 2, role: "歌唱（グループ）" },
        { id: 65, workId: 23, groupId: 2, role: "歌唱（グループ）" },
        { id: 66, workId: 24, groupId: 2, role: "歌唱（グループ）" },
        { id: 67, workId: 25, groupId: 2, role: "歌唱（グループ）" },
        { id: 68, workId: 26, groupId: 2, role: "歌唱（グループ）" },
        { id: 69, workId: 9, groupId: 3, role: "歌唱（グループ）" },
        { id: 70, workId: 27, groupId: 3, role: "歌唱（グループ）" },
        { id: 71, workId: 28, groupId: 3, role: "歌唱（グループ）" },
        { id: 72, workId: 29, groupId: 3, role: "歌唱（グループ）" },
        { id: 73, workId: 30, groupId: 3, role: "歌唱（グループ）" },
        { id: 74, workId: 10, groupId: 6, role: "歌唱（グループ）" },
        { id: 75, workId: 8, groupId: 8, role: "歌唱（グループ）" },
        { id: 76, workId: 132, groupId: 12, role: "歌唱（グループ）" },
        { id: 77, workId: 135, groupId: 13, role: "出演（グループ）" },
        { id: 78, workId: 136, groupId: 14, role: "歌唱（グループ）" },
        { id: 79, workId: 137, groupId: 14, role: "歌唱（グループ）" },
        { id: 80, workId: 138, groupId: 14, role: "歌唱（グループ）" },
        { id: 81, workId: 140, groupId: 15, role: "歌唱（グループ）" },
        { id: 82, workId: 141, groupId: 15, role: "歌唱（グループ）" },
        { id: 83, workId: 142, groupId: 16, role: "歌唱（グループ）" },
        { id: 84, workId: 143, groupId: 16, role: "歌唱（グループ）" },
        { id: 85, workId: 144, groupId: 16, role: "歌唱（グループ）" },
        { id: 86, workId: 7, groupId: 17, role: "歌唱（グループ）" },
        { id: 87, workId: 145, groupId: 17, role: "歌唱（グループ）" },
        { id: 88, workId: 146, groupId: 17, role: "歌唱（グループ）" },
        { id: 89, workId: 4, idolId: 6, role: "歌唱" },
        { id: 90, workId: 4, idolId: 7, role: "歌唱" },
        { id: 91, workId: 4, idolId: 8, role: "歌唱" },
        { id: 92, workId: 4, idolId: 9, role: "歌唱" },
        { id: 93, workId: 4, idolId: 10, role: "歌唱" },
        { id: 94, workId: 4, idolId: 11, role: "歌唱" }
    ],
    live: [
        { id: 1, name: "ARASHI Anniversary Tour 5×20", date: "2019-12-25", venueId: 1 },
        { id: 2, name: "慣声の法則", date: "2023-01-05", venueId: 2 },
        { id: 3, name: "Snow Man LIVE TOUR 2024", date: "2024-11-15", venueId: 3 },
        { id: 4, name: "King & Prince LIVE TOUR 2023 ~ピース~", date: "2023-08-27", venueId: 2 },
        { id: 5, name: "KinKi Kids Concert 2023-2024", date: "2023-12-16", venueId: 1 },
        { id: 6, name: "KAT-TUN LIVE TOUR 2023 Fantasia", date: "2023-05-03", venueId: 2 },
        { id: 7, name: "アラフェス 2020 at 国立競技場", date: "2020-11-03", venueId: 7 },
        { id: 8, name: "WE ARE! Let's get the party STARTO!!", date: "2024-04-10", venueId: 1 },
        { id: 9, name: "なにわ男子 LIVE TOUR 2024", date: "2024-08-10", venueId: 4 },
        { id: 10, name: "WEST. DOME TOUR AWARD", date: "2024-07-14", venueId: 3 },
        { id: 11, name: "Aぇ! group Debut Tour", date: "2024-06-01", venueId: 2 },
        { id: 12, name: "Travis Japan World Tour Showcase", date: "2024-09-03", venueId: 8 },
        { id: 13, name: "SUPER EIGHT 超アリーナツアー", date: "2024-10-01", venueId: 4 },
        { id: 14, name: "timelesz episode 0", date: "2024-06-22", venueId: 9 }
    ],
    venue: [
        { id: 1, name: "東京ドーム", location: "東京都", capacity: 55000 },
        { id: 2, name: "横浜アリーナ", location: "神奈川県", capacity: 17000 },
        { id: 3, name: "京セラドーム大阪", location: "大阪府", capacity: 55000 },
        { id: 4, name: "さいたまスーパーアリーナ", location: "埼玉県", capacity: 37000 },
        { id: 5, name: "福岡PayPayドーム", location: "福岡県", capacity: 38500 },
        { id: 6, name: "バンテリンドーム ナゴヤ", location: "愛知県", capacity: 40500 },
        { id: 7, name: "国立競技場", location: "東京都", capacity: 68000 },
        { id: 8, name: "台北アリーナ", location: "台湾", capacity: 15000 },
        { id: 9, name: "大阪城ホール", location: "大阪府", capacity: 16000 },
        { id: 10, name: "マリンメッセ福岡", location: "福岡県", capacity: 15000 }
    ],
    liveCast: [
        { id: 1, liveId: 1, groupId: 1 },
        { id: 2, liveId: 2, groupId: 2 },
        { id: 3, liveId: 3, groupId: 3 },
        { id: 4, liveId: 4, groupId: 8 },
        { id: 5, liveId: 5, groupId: 17 },
        { id: 6, liveId: 6, groupId: 6 },
        { id: 7, liveId: 7, groupId: 1 },
        { id: 8, liveId: 8, groupId: 2 },
        { id: 9, liveId: 8, groupId: 3 },
        { id: 10, liveId: 8, groupId: 8 },
        { id: 11, liveId: 8, groupId: 11 },
        { id: 12, liveId: 8, groupId: 12 },
        { id: 13, liveId: 8, groupId: 13 },
        { id: 14, liveId: 9, groupId: 11 },
        { id: 15, liveId: 10, groupId: 10 },
        { id: 16, liveId: 11, groupId: 13 },
        { id: 17, liveId: 12, groupId: 12 },
        { id: 18, liveId: 14, groupId: 9 }
    ],
    event: [
        { id: 1, date: "1999-09-15", type: "結成", description: "嵐 結成" },
        { id: 2, date: "2020-01-22", type: "デビュー", description: "SixTONES デビュー" },
        { id: 3, date: "2024-02-04", type: "改名", description: "関ジャニ∞ → SUPER EIGHT" },
        { id: 4, date: "2020-12-31", type: "活動休止", description: "嵐 活動休止" },
        { id: 5, date: "1997-07-21", type: "デビュー", description: "KinKi Kids CDデビュー (ミリオンセラー達成)" },
        { id: 6, date: "2006-03-22", type: "デビュー", description: "KAT-TUN デビューシングル・アルバム・DVD同時発売" },
        { id: 7, date: "2018-05-23", type: "デビュー", description: "King & Prince CDデビュー" },
        { id: 8, date: "2023-05-22", type: "脱退", description: "平野紫耀・神宮寺勇太・岸優太 King & Prince脱退" },
        { id: 9, date: "1994-09-21", type: "デビュー", description: "TOKIO CDデビュー" },
        { id: 10, date: "1995-11-01", type: "デビュー", description: "V6 CDデビュー" },
        { id: 11, date: "2003-11-07", type: "デビュー", description: "NEWS CDデビュー" },
        { id: 12, date: "2004-08-25", type: "デビュー", description: "関ジャニ∞ 関西限定CDデビュー" },
        { id: 13, date: "2004-09-22", type: "デビュー", description: "関ジャニ∞ 全国CDデビュー" },
        { id: 14, date: "2007-11-14", type: "デビュー", description: "Hey! Say! JUMP CDデビュー・東京ドーム公演" },
        { id: 15, date: "2008-09-05", type: "その他", description: "嵐 国立競技場での初ライブ「ARASHI AROUND ASIA 2008」" },
        { id: 16, date: "2011-08-10", type: "デビュー", description: "Kis-My-Ft2 CDデビュー" },
        { id: 17, date: "2011-11-16", type: "デビュー", description: "Sexy Zone CDデビュー" },
        { id: 18, date: "2014-04-23", type: "デビュー", description: "ジャニーズWEST CDデビュー" },
        { id: 19, date: "2015-05-01", type: "結成", description: "SixTONES 結成" },
        { id: 20, date: "2020-01-22", type: "デビュー", description: "Snow Man CDデビュー (SixTONESと同時)" },
        { id: 21, date: "2021-11-12", type: "デビュー", description: "なにわ男子 CDデビュー" },
        { id: 22, date: "2022-10-28", type: "デビュー", description: "Travis Japan 全世界配信デビュー" },
        { id: 23, date: "2023-11-03", type: "その他", description: "嵐 デビュー25周年" },
        { id: 24, date: "2024-04-10", type: "その他", description: "STARTO ENTERTAINMENT合同ライブ「WE ARE!」開催" },
        { id: 25, date: "2024-05-15", type: "デビュー", description: "Aぇ! group CDデビュー" },
        { id: 26, date: "2006-03-22", type: "その他", description: "KAT-TUN シングル・アルバム・DVD同時発売ミリオン達成" },
        { id: 27, date: "2022-12-03", type: "その他", description: "King & Prince 「ツキヨミ」ミリオンセラー達成" }
    ]
};

let counters = { agency: 3, group: 18, idol: 95, affiliation: 97, groupHistory: 7, work: 147, participation: 95, live: 15, venue: 11, liveCast: 19, event: 28 };
